---
# This playbook installs all the prerequisites needed for OpsHub Integration Manager with a local MySQL database
- hosts: localhost

  roles:
    # GNOME desktop is needed to run the graphical OIM installer
    - role: gnome
      tags: gnome
    # VNC server is needed to run the graphical OIM installer
    - role: vnc
      tags: vnc
    # We are using a MySQL database on the same server as OIM itself
    - role: mysql
      tags: mysql
    # Load DCSS root certificates so that https connections to GitLab will be trusted
    - role: certs
      tags: certs
    # OIM setup
    - role: oim
      tags: oim
  vars:

    # Anyone who needs to run the OIM graphical installer should be added to this vnc_users section.
    # This should just be the person(s) doing the install. Once OIM is installed, OIM users don't need VNC access to the server, they access OIM through a browser.
    # Specify three values for each user who will run the graphical installer:
    #  their linux userid
    #  what display port to use (start at 2 and increment per user) - this is what port to tunnel and what display to connect to.  2 = port 5902 and a VNC connection to localhost::5902, 3 = port 5903, etc.
    #  what to set their VNC password to, the VNC client will prompt for this when connecting
    vnc_users:
      - userid: ec2-user
        display: 2
        vnc_password: dcssvnc
<<<<<<< HEAD
=======
      - userid: aramagiri
        display: 3
        vnc_password: dcssvnc
      - userid: krondla
        display: 5
        vnc_password: dcssvnc
>>>>>>> 8afd6fae9e718a4935d551828d87f67edb5278ac

    # Set passwords for MySQL userids
    # TODO root_password handling not yet working on a clean install
    mysql:
      oim_mysql_password: OimAdmin2018#

    # DNS name and internal IP address of the GitLab server that OIM will connect to
    # This is necssary for some host file and SSL certificate trickery because
    #   the network firewall only allows the oim server to connect to the gitlab server on the gitlab server's internal IP address
    #   yet the gitlab server's DNS name maps to the gitlab server's external IP address (which is blocked)
    gitlab:
      dns_name: gitlab.dcss.ca.gov
      short_name: gitlab
      internal_IP_address: 100.95.22.13
